export { IVuexModule } from './i-vuex-module'
export { IHttpModule } from './i-http-module'
export { ICartRootProperties } from './i-cart-root-properties'
export { ILocation } from './i-location'
export { IServiceCtor } from './i-service-ctor'